<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>nc</string>
		<string>ngc</string>
		<string>prg</string>
		<string>mpf</string>
		<string>gcode</string>
	</array>
	<key>name</key>
	<string>Grbl</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>comment</key>
			<string>invalid g commands</string>
			<key>match</key>
			<string>G[0-9][0-9][0-9]+</string>
			<key>name</key>
			<string>invalid.deprecated</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>invalid g command G52</string>
			<key>match</key>
			<string>G52</string>
			<key>name</key>
			<string>invalid.deprecated</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Set WCS</string>
			<key>match</key>
			<string>G10 L20 P[1-4]</string>
			<key>name</key>
			<string>support.function</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>G1 - G4 commands</string>
			<key>match</key>
			<string>(G[0-4][ ])</string>
			<key>name</key>
			<string>string</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>G17 - G19 commands</string>
			<key>match</key>
			<string>(G1[7-9])</string>
			<key>name</key>
			<string>string</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>G20 - G21 commands</string>
			<key>match</key>
			<string>(G2[01])</string>
			<key>name</key>
			<string>string</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>G28 commands</string>
			<key>match</key>
			<string>(G28\.?1? )</string>
			<key>name</key>
			<string>string</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>G30 commands</string>
			<key>match</key>
			<string>(G30(\.1)? )</string>
			<key>name</key>
			<string>string</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>G38 commands</string>
			<key>match</key>
			<string>(G38(\.2)? )</string>
			<key>name</key>
			<string>string</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>G53 - G59 commands</string>
			<key>match</key>
			<string>(G5[3-9] )</string>
			<key>name</key>
			<string>string</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>G90 - G91 commands</string>
			<key>match</key>
			<string>(G9[01])</string>
			<key>name</key>
			<string>string</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>G92.1 commands</string>
			<key>match</key>
			<string>(G92\.1)</string>
			<key>name</key>
			<string>string</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>G93 - G94 commands</string>
			<key>match</key>
			<string>(G9[34])</string>
			<key>name</key>
			<string>string</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>M3 - M9 commands</string>
			<key>match</key>
			<string>(M[34589])</string>
			<key>name</key>
			<string>support.constant</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>M30 commands</string>
			<key>match</key>
			<string>(M30[ ])</string>
			<key>name</key>
			<string>support.constant</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>M100 - M101 commands</string>
			<key>match</key>
			<string>(M10[01][ ])</string>
			<key>name</key>
			<string>support.constant</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>comments</string>
			<key>match</key>
			<string>\(.*\)</string>
			<key>name</key>
			<string>comment.line</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>variables</string>
			<key>match</key>
			<string>(#\d+)</string>
			<key>name</key>
			<string>variable.other</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>z-position</string>
			<key>match</key>
			<string>(Z-?\d+[\.]*\d*)</string>
			<key>name</key>
			<string>variable</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>positions</string>
			<key>match</key>
			<string>([XY]-?\d+\.*\d*)</string>
			<key>name</key>
			<string>support.class</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>arc positions</string>
			<key>match</key>
			<string>([IJK]-?\d+\.*\d*)</string>
			<key>name</key>
			<string>constant.other.color</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>feeds &amp; speeds</string>
			<key>match</key>
			<string>(?&lt;= )[FS]([\d\.-])+</string>
			<key>name</key>
			<string>variable.parameter</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>O &amp; N numbers</string>
			<key>match</key>
			<string>([ON]([\d\.-])+)</string>
			<key>name</key>
			<string>support.function</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>brackets</string>
			<key>match</key>
			<string>(\[|\])</string>
			<key>name</key>
			<string>string.interpolated</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.grbl</string>
	<key>uuid</key>
	<string>7287ac7d-bcc9-11e6-855b-f45c89998e31</string>
</dict>
</plist>
